/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanos;

/**
 *
 * @author CyA
 */
import java.util.*;

public class Romanos {

    public static void main(String[] args) {
    System.out.println("Bienvenido al convertidor de numeros romanos");
    System.out.println("Introduzca el número del 1 al 1000 que desea convertir");
    Scanner sc = new Scanner(System.in);
    int resp = sc.nextInt();
    
    if (resp==1){ System.out.println("La conversión es: I");}
    if (resp==2){ System.out.println("La conversión es: II");}
    if (resp==3){ System.out.println("La conversión es: III");}
    if (resp==4){ System.out.println("La conversión es: IV");}  
    if (resp==5){ System.out.println("La conversión es: V");}
    if (resp==6){ System.out.println("La conversión es: VI");}
    if (resp==7){ System.out.println("La conversión es: VII");}
    if (resp==8){ System.out.println("La conversión es: VIII");}
    if (resp==9){ System.out.println("La conversión es: IX");}
    if (resp==10){ System.out.println("La conversión es: X");}
    if (resp==11){ System.out.println("La conversión es: XI");}
    if (resp==12){ System.out.println("La conversión es: XII");}
    if (resp==13){ System.out.println("La conversión es: XIII");}
    if (resp==14){ System.out.println("La conversión es: XIV");}
    if (resp==15){ System.out.println("La conversión es: XV");}
    if (resp==16){ System.out.println("La conversión es: XVI");}
    if (resp==17){ System.out.println("La conversión es: XVII");}
    if (resp==18){ System.out.println("La conversión es: XVIII");}
    if (resp==19){ System.out.println("La conversión es: XIX");}
    if (resp==20){ System.out.println("La conversión es: XX");}
    if (resp==21){ System.out.println("La conversión es: XXI");}
    if (resp==22){ System.out.println("La conversión es: XXII");}
    if (resp==23){ System.out.println("La conversión es: XXIII");}
    if (resp==24){ System.out.println("La conversión es: XXIV");}
    if (resp==25){ System.out.println("La conversión es: XXV");}
    if (resp==26){ System.out.println("La conversión es: XXVI");}
    if (resp==27){ System.out.println("La conversión es: XXVII");}
    if (resp==28){ System.out.println("La conversión es: XXVIII");}
    if (resp==29){ System.out.println("La conversión es: XXIX");}  
    if (resp==30){ System.out.println("La conversión es: XXX");}
    if (resp==31){ System.out.println("La conversión es: XXXI");}
    if (resp==32){ System.out.println("La conversión es: XXXII");}
    if (resp==33){ System.out.println("La conversión es: XXXIII");}
    if (resp==34){ System.out.println("La conversión es: XXXIV");}
    if (resp==35){ System.out.println("La conversión es: XXXV");}
    if (resp==36){ System.out.println("La conversión es: XXXVI");}
    if (resp==37){ System.out.println("La conversión es: XXXVII");}
    if (resp==38){ System.out.println("La conversión es: XXXVIII");}
    if (resp==39){ System.out.println("La conversión es: XXXIX");}
    if (resp==40){ System.out.println("La conversión es: XL");}
    if (resp==41){ System.out.println("La conversión es: XLI");}
    if (resp==42){ System.out.println("La conversión es: XLII");}
    if (resp==43){ System.out.println("La conversión es: XLIII");}
    if (resp==44){ System.out.println("La conversión es: XLIV");}
    if (resp==45){ System.out.println("La conversión es: XLV");}
    if (resp==46){ System.out.println("La conversión es: XLVI");}
    if (resp==47){ System.out.println("La conversión es: XLVII");}
    if (resp==48){ System.out.println("La conversión es: XLVIII");}
    if (resp==49){ System.out.println("La conversión es: XLIX");}
    if (resp==50){ System.out.println("La conversión es: L");}
    if (resp==51){ System.out.println("La conversión es: LI");}
    if (resp==52){ System.out.println("La conversión es: LII");}
    if (resp==53){ System.out.println("La conversión es: LIII");}
    if (resp==54){ System.out.println("La conversión es: LIV");}
    if (resp==55){ System.out.println("La conversión es: LV");}
    if (resp==56){ System.out.println("La conversión es: LVI");}
    if (resp==57){ System.out.println("La conversión es: LVII");}  
    if (resp==58){ System.out.println("La conversión es: LVIII");}
    if (resp==59){ System.out.println("La conversión es: LIX");}
    if (resp==60){ System.out.println("La conversión es: LX");}
    if (resp==61){ System.out.println("La conversión es: LXI");}
    if (resp==62){ System.out.println("La conversión es: LXII");}
    if (resp==63){ System.out.println("La conversión es: LXIII");}
    if (resp==64){ System.out.println("La conversión es: LXIV");}
    if (resp==65){ System.out.println("La conversión es: LXV");}
    if (resp==66){ System.out.println("La conversión es: LXVI");}
    if (resp==67){ System.out.println("La conversión es: LXVII");}
    if (resp==68){ System.out.println("La conversión es: LXVIII");}
    if (resp==69){ System.out.println("La conversión es: LXIX");}
    if (resp==70){ System.out.println("La conversión es: LXX");}
    if (resp==71){ System.out.println("La conversión es: LXXI");}
    if (resp==72){ System.out.println("La conversión es: LXXII");}
    if (resp==73){ System.out.println("La conversión es: LXXIII");}
    if (resp==74){ System.out.println("La conversión es: LXXIV");}
    if (resp==75){ System.out.println("La conversión es: LXXV");}
    if (resp==76){ System.out.println("La conversión es: LXXVI");}
    if (resp==77){ System.out.println("La conversión es: LXXVII");}
    if (resp==78){ System.out.println("La conversión es: LXXVIII");}
    if (resp==79){ System.out.println("La conversión es: LXXIX");}
    if (resp==80){ System.out.println("La conversión es: LXXX");}
    if (resp==81){ System.out.println("La conversión es: LXXXI");}
    if (resp==82){ System.out.println("La conversión es: LXXXII");}  
    if (resp==83){ System.out.println("La conversión es: LXXXIII");}
    if (resp==84){ System.out.println("La conversión es: LXXXIV");}
    if (resp==85){ System.out.println("La conversión es: LXXXV");}
    if (resp==86){ System.out.println("La conversión es: LXXXVI");}
    if (resp==87){ System.out.println("La conversión es: LXXXVII");}
    if (resp==88){ System.out.println("La conversión es: LXXXVIII");}
    if (resp==89){ System.out.println("La conversión es: LXXXIX");}
    if (resp==90){ System.out.println("La conversión es: XC");}
    if (resp==91){ System.out.println("La conversión es: XCI");}
    if (resp==92){ System.out.println("La conversión es: XCII");}
    if (resp==93){ System.out.println("La conversión es: XCIII");}
    if (resp==94){ System.out.println("La conversión es: XCIV");}
    if (resp==95){ System.out.println("La conversión es: XCV");}
    if (resp==96){ System.out.println("La conversión es: XCVI");}
    if (resp==97){ System.out.println("La conversión es: XCVII");}
    if (resp==98){ System.out.println("La conversión es: XCVIII");}
    if (resp==99){ System.out.println("La conversión es: XCIX");}
    
    if (resp==100){ System.out.println("La conversión es: C");}
    if (resp==101){ System.out.println("La conversión es: CI");}
    if (resp==102){ System.out.println("La conversión es: CII");}
    if (resp==103){ System.out.println("La conversión es: CIII");}
    if (resp==104){ System.out.println("La conversión es: CIV");}
    if (resp==105){ System.out.println("La conversión es: CV");}
    if (resp==106){ System.out.println("La conversión es: CVI");}
    if (resp==107){ System.out.println("La conversión es: CVII");}
    if (resp==108){ System.out.println("La conversión es: CVIII");}
    if (resp==109){ System.out.println("La conversión es: CIX");}
    if (resp==110){ System.out.println("La conversión es: CX");}
    if (resp==111){ System.out.println("La conversión es: CXI");}
    if (resp==112){ System.out.println("La conversión es: CXII");}
    if (resp==113){ System.out.println("La conversión es: CXIII");}
    if (resp==114){ System.out.println("La conversión es: CXIV");}
    if (resp==115){ System.out.println("La conversión es: CXV");}
    if (resp==116){ System.out.println("La conversión es: CXVI");}
    if (resp==117){ System.out.println("La conversión es: CXVII");}
    if (resp==118){ System.out.println("La conversión es: CXVIII");}
    if (resp==119){ System.out.println("La conversión es: CXIX");}
    if (resp==120){ System.out.println("La conversión es: CXX");}
    if (resp==121){ System.out.println("La conversión es: CXXI");}
    if (resp==122){ System.out.println("La conversión es: CXXII");}
    if (resp==123){ System.out.println("La conversión es: CXXIII");}
    if (resp==124){ System.out.println("La conversión es: CXXIV");}
    if (resp==125){ System.out.println("La conversión es: CXXV");}
    if (resp==126){ System.out.println("La conversión es: CXXVI");}
    if (resp==127){ System.out.println("La conversión es: CXXVII");}
    if (resp==128){ System.out.println("La conversión es: CXXVIII");}
    if (resp==129){ System.out.println("La conversión es: CXXIX");}  
    if (resp==130){ System.out.println("La conversión es: CXXX");}
    if (resp==131){ System.out.println("La conversión es: CXXXI");}
    if (resp==132){ System.out.println("La conversión es: CXXXII");}
    if (resp==133){ System.out.println("La conversión es: CXXXIII");}
    if (resp==134){ System.out.println("La conversión es: CXXXIV");}
    if (resp==135){ System.out.println("La conversión es: CXXXV");}
    if (resp==136){ System.out.println("La conversión es: CXXXVI");}
    if (resp==137){ System.out.println("La conversión es: CXXXVII");}
    if (resp==138){ System.out.println("La conversión es: CXXXVIII");}
    if (resp==139){ System.out.println("La conversión es: CXXXIX");}
    if (resp==140){ System.out.println("La conversión es: CXL");}
    if (resp==141){ System.out.println("La conversión es: CXLI");}
    if (resp==142){ System.out.println("La conversión es: CXLII");}
    if (resp==143){ System.out.println("La conversión es: CXLIII");}
    if (resp==144){ System.out.println("La conversión es: CXLIV");}
    if (resp==145){ System.out.println("La conversión es: CXLV");}
    if (resp==146){ System.out.println("La conversión es: CXLVI");}
    if (resp==147){ System.out.println("La conversión es: CXLVII");}
    if (resp==148){ System.out.println("La conversión es: CXLVIII");}
    if (resp==149){ System.out.println("La conversión es: CXLIX");}
    if (resp==150){ System.out.println("La conversión es: CL");}
    if (resp==151){ System.out.println("La conversión es: CLI");}
    if (resp==152){ System.out.println("La conversión es: CLII");}
    if (resp==153){ System.out.println("La conversión es: CLIII");}
    if (resp==154){ System.out.println("La conversión es: CLIV");}
    if (resp==155){ System.out.println("La conversión es: CLV");}
    if (resp==156){ System.out.println("La conversión es: CLCVI");}
    if (resp==157){ System.out.println("La conversión es: CLVII");}  
    if (resp==158){ System.out.println("La conversión es: CLVIII");}
    if (resp==159){ System.out.println("La conversión es: CLIX");}
    if (resp==160){ System.out.println("La conversión es: CLX");}
    if (resp==161){ System.out.println("La conversión es: CLXI");}
    if (resp==162){ System.out.println("La conversión es: CLXII");}
    if (resp==163){ System.out.println("La conversión es: CLXIII");}
    if (resp==164){ System.out.println("La conversión es: CLXIV");}
    if (resp==165){ System.out.println("La conversión es: CLXV");}
    if (resp==166){ System.out.println("La conversión es: CLXVI");}
    if (resp==167){ System.out.println("La conversión es: CLXVII");}
    if (resp==168){ System.out.println("La conversión es: CLXVIII");}
    if (resp==169){ System.out.println("La conversión es: CLXIX");}
    if (resp==170){ System.out.println("La conversión es: CLXX");}
    if (resp==171){ System.out.println("La conversión es: CLXXI");}
    if (resp==172){ System.out.println("La conversión es: CLXXII");}
    if (resp==173){ System.out.println("La conversión es: CLXXIII");}
    if (resp==174){ System.out.println("La conversión es: CLXXIV");}
    if (resp==175){ System.out.println("La conversión es: CLXXV");}
    if (resp==176){ System.out.println("La conversión es: CLXXVI");}
    if (resp==177){ System.out.println("La conversión es: CLXXVII");}
    if (resp==178){ System.out.println("La conversión es: CLXXVIII");}
    if (resp==179){ System.out.println("La conversión es: CLXXIX");}
    if (resp==180){ System.out.println("La conversión es: CLXXX");}
    if (resp==181){ System.out.println("La conversión es: CLXXXI");}
    if (resp==182){ System.out.println("La conversión es: CLXXXII");}  
    if (resp==183){ System.out.println("La conversión es: CLXXXIII");}
    if (resp==184){ System.out.println("La conversión es: CLXXXIV");}
    if (resp==185){ System.out.println("La conversión es: CLXXXV");}
    if (resp==186){ System.out.println("La conversión es: CLXXXVI");}
    if (resp==187){ System.out.println("La conversión es: CLXXXVII");}
    if (resp==188){ System.out.println("La conversión es: CLXXXVIII");}
    if (resp==189){ System.out.println("La conversión es: CLXXXIX");}
    if (resp==190){ System.out.println("La conversión es: CXC");}
    if (resp==191){ System.out.println("La conversión es: CXCI");}
    if (resp==192){ System.out.println("La conversión es: CXCII");}
    if (resp==193){ System.out.println("La conversión es: CXCIII");}
    if (resp==194){ System.out.println("La conversión es: CXCIV");}
    if (resp==195){ System.out.println("La conversión es: CXCV");}
    if (resp==196){ System.out.println("La conversión es: CXCVI");}
    if (resp==197){ System.out.println("La conversión es: CXCVII");}
    if (resp==198){ System.out.println("La conversión es: CXCVIII");}
    if (resp==199){ System.out.println("La conversión es: CXCIX");}
    
    if (resp==200){ System.out.println("La conversión es: CC");}
    if (resp==201){ System.out.println("La conversión es: CCI");}
    if (resp==202){ System.out.println("La conversión es: CCII");}
    if (resp==203){ System.out.println("La conversión es: CCIII");}
    if (resp==204){ System.out.println("La conversión es: CCIV");}  
    if (resp==205){ System.out.println("La conversión es: CCV");}
    if (resp==206){ System.out.println("La conversión es: CCVI");}
    if (resp==207){ System.out.println("La conversión es: CCVII");}
    if (resp==208){ System.out.println("La conversión es: CCVIII");}
    if (resp==209){ System.out.println("La conversión es: CCIX");}
    if (resp==210){ System.out.println("La conversión es: CCX");}
    if (resp==211){ System.out.println("La conversión es: CCXI");}
    if (resp==212){ System.out.println("La conversión es: CCXII");}
    if (resp==213){ System.out.println("La conversión es: CCXIII");}
    if (resp==214){ System.out.println("La conversión es: CCXIV");}
    if (resp==215){ System.out.println("La conversión es: CCXV");}
    if (resp==216){ System.out.println("La conversión es: CCXVI");}
    if (resp==217){ System.out.println("La conversión es: CCXVII");}
    if (resp==218){ System.out.println("La conversión es: CCXVIII");}
    if (resp==219){ System.out.println("La conversión es: CCXIX");}
    if (resp==220){ System.out.println("La conversión es: CCXX");}
    if (resp==221){ System.out.println("La conversión es: CCXXI");}
    if (resp==222){ System.out.println("La conversión es: CCXXII");}
    if (resp==223){ System.out.println("La conversión es: CCXXIII");}
    if (resp==224){ System.out.println("La conversión es: CCXXIV");}
    if (resp==225){ System.out.println("La conversión es: CCXXV");}
    if (resp==226){ System.out.println("La conversión es: CCXXVI");}
    if (resp==227){ System.out.println("La conversión es: CCXXVII");}
    if (resp==228){ System.out.println("La conversión es: CCXXVIII");}
    if (resp==229){ System.out.println("La conversión es: CCXXIX");}  
    if (resp==230){ System.out.println("La conversión es: CCXXX");}
    if (resp==231){ System.out.println("La conversión es: CCXXXI");}
    if (resp==232){ System.out.println("La conversión es: CCXXXII");}
    if (resp==233){ System.out.println("La conversión es: CCXXXIII");}
    if (resp==234){ System.out.println("La conversión es: CCXXXIV");}
    if (resp==235){ System.out.println("La conversión es: CCXXXV");}
    if (resp==236){ System.out.println("La conversión es: CCXXXVI");}
    if (resp==237){ System.out.println("La conversión es: CCXXXVII");}
    if (resp==238){ System.out.println("La conversión es: CCXXXVIII");}
    if (resp==239){ System.out.println("La conversión es: CCXXXIX");}
    if (resp==240){ System.out.println("La conversión es: CCXL");}
    if (resp==241){ System.out.println("La conversión es: CCXLI");}
    if (resp==242){ System.out.println("La conversión es: CCXLII");}
    if (resp==243){ System.out.println("La conversión es: CCXLIII");}
    if (resp==244){ System.out.println("La conversión es: CCXLIV");}
    if (resp==245){ System.out.println("La conversión es: CCXLV");}
    if (resp==246){ System.out.println("La conversión es: CCXLVI");}
    if (resp==247){ System.out.println("La conversión es: CCXLVII");}
    if (resp==248){ System.out.println("La conversión es: CCXLVIII");}
    if (resp==249){ System.out.println("La conversión es: CCXLIX");}
    if (resp==250){ System.out.println("La conversión es: CCL");}
    if (resp==251){ System.out.println("La conversión es: CCLI");}
    if (resp==252){ System.out.println("La conversión es: CCLII");}
    if (resp==253){ System.out.println("La conversión es: CCLIII");}
    if (resp==254){ System.out.println("La conversión es: CCLIV");}
    if (resp==255){ System.out.println("La conversión es: CCLV");}
    if (resp==256){ System.out.println("La conversión es: CCLVI");}
    if (resp==257){ System.out.println("La conversión es: CCLVII");}  
    if (resp==258){ System.out.println("La conversión es: CCLVIII");}
    if (resp==259){ System.out.println("La conversión es: CCLIX");}
    if (resp==260){ System.out.println("La conversión es: CCLX");}
    if (resp==261){ System.out.println("La conversión es: CCLXI");}
    if (resp==262){ System.out.println("La conversión es: CCLXII");}
    if (resp==263){ System.out.println("La conversión es: CCLXIII");}
    if (resp==264){ System.out.println("La conversión es: CCLXIV");}
    if (resp==265){ System.out.println("La conversión es: CCLXV");}
    if (resp==266){ System.out.println("La conversión es: CCLXVI");}
    if (resp==267){ System.out.println("La conversión es: CCLXVII");}
    if (resp==268){ System.out.println("La conversión es: CCLXVIII");}
    if (resp==269){ System.out.println("La conversión es: CCLXIX");}
    if (resp==270){ System.out.println("La conversión es: CCLXX");}
    if (resp==271){ System.out.println("La conversión es: CCLXXI");}
    if (resp==272){ System.out.println("La conversión es: CCLXXII");}
    if (resp==273){ System.out.println("La conversión es: CCLXXIII");}
    if (resp==274){ System.out.println("La conversión es: CCLXXIV");}
    if (resp==275){ System.out.println("La conversión es: CCLXXV");}
    if (resp==276){ System.out.println("La conversión es: CCLXXVI");}
    if (resp==277){ System.out.println("La conversión es: CCLXXVII");}
    if (resp==278){ System.out.println("La conversión es: CCLXXVIII");}
    if (resp==279){ System.out.println("La conversión es: CCLXXIX");}
    if (resp==280){ System.out.println("La conversión es: CCLXXX");}
    if (resp==281){ System.out.println("La conversión es: CCLXXXI");}
    if (resp==282){ System.out.println("La conversión es: CCLXXXII");}  
    if (resp==283){ System.out.println("La conversión es: CCLXXXIII");}
    if (resp==284){ System.out.println("La conversión es: CCLXXXIV");}
    if (resp==285){ System.out.println("La conversión es: CCLXXXV");}
    if (resp==286){ System.out.println("La conversión es: CCLXXXVI");}
    if (resp==287){ System.out.println("La conversión es: CCLXXXVII");}
    if (resp==288){ System.out.println("La conversión es: CCLXXXVIII");}
    if (resp==289){ System.out.println("La conversión es: CCLXXXIX");}
    if (resp==290){ System.out.println("La conversión es: CCXC");}
    if (resp==291){ System.out.println("La conversión es: CCXCI");}
    if (resp==292){ System.out.println("La conversión es: CCXCII");}
    if (resp==293){ System.out.println("La conversión es: CCXCIII");}
    if (resp==294){ System.out.println("La conversión es: CCXCIV");}
    if (resp==295){ System.out.println("La conversión es: CCXCV");}
    if (resp==296){ System.out.println("La conversión es: CCXCVI");}
    if (resp==297){ System.out.println("La conversión es: CCXCVII");}
    if (resp==298){ System.out.println("La conversión es: CCXCVIII");}
    if (resp==299){ System.out.println("La conversión es: CCXCIX");}
    if (resp==300){ System.out.println("La conversión es: CCC");}
    
    if (resp==301){ System.out.println("La conversión es: CCCI");}
    if (resp==302){ System.out.println("La conversión es: CCCII");}
    if (resp==303){ System.out.println("La conversión es: CCCIII");}
    if (resp==304){ System.out.println("La conversión es: CCCIV");}  
    if (resp==305){ System.out.println("La conversión es: CCCV");}
    if (resp==306){ System.out.println("La conversión es: CCCVI");}
    if (resp==307){ System.out.println("La conversión es: CCCVII");}
    if (resp==308){ System.out.println("La conversión es: CCCVIII");}
    if (resp==309){ System.out.println("La conversión es: CCCIX");}
    if (resp==310){ System.out.println("La conversión es: CCCX");}
    if (resp==311){ System.out.println("La conversión es: CCCXI");}
    if (resp==312){ System.out.println("La conversión es: CCCXII");}
    if (resp==313){ System.out.println("La conversión es: CCCXIII");}
    if (resp==314){ System.out.println("La conversión es: CCCXIV");}
    if (resp==315){ System.out.println("La conversión es: CCCXV");}
    if (resp==316){ System.out.println("La conversión es: CCCXVI");}
    if (resp==317){ System.out.println("La conversión es: CCCXVII");}
    if (resp==318){ System.out.println("La conversión es: CCCXVIII");}
    if (resp==319){ System.out.println("La conversión es: CCCXIX");}
    if (resp==320){ System.out.println("La conversión es: CCCXX");}
    if (resp==321){ System.out.println("La conversión es: CCCXXI");}
    if (resp==322){ System.out.println("La conversión es: CCCXXII");}
    if (resp==323){ System.out.println("La conversión es: CCCXXIII");}
    if (resp==324){ System.out.println("La conversión es: CCCXXIV");}
    if (resp==325){ System.out.println("La conversión es: CCCXXV");}
    if (resp==326){ System.out.println("La conversión es: CCCXXVI");}
    if (resp==327){ System.out.println("La conversión es: CCCXXVII");}
    if (resp==328){ System.out.println("La conversión es: CCCXXVIII");}
    if (resp==329){ System.out.println("La conversión es: CCCXXIX");}  
    if (resp==330){ System.out.println("La conversión es: CCCXXX");}
    if (resp==331){ System.out.println("La conversión es: CCCXXXI");}
    if (resp==332){ System.out.println("La conversión es: CCCXXXII");}
    if (resp==333){ System.out.println("La conversión es: CCCXXXIII");}
    if (resp==334){ System.out.println("La conversión es: CCCXXXIV");}
    if (resp==335){ System.out.println("La conversión es: CCCXXXV");}
    if (resp==336){ System.out.println("La conversión es: CCCXXXVI");}
    if (resp==337){ System.out.println("La conversión es: CCCXXXVII");}
    if (resp==338){ System.out.println("La conversión es: CCCXXXVIII");}
    if (resp==339){ System.out.println("La conversión es: CCCXXXIX");}
    if (resp==340){ System.out.println("La conversión es: CCCXL");}
    if (resp==341){ System.out.println("La conversión es: CCCXLI");}
    if (resp==342){ System.out.println("La conversión es: CCCXLII");}
    if (resp==343){ System.out.println("La conversión es: CCCXLIII");}
    if (resp==344){ System.out.println("La conversión es: CCCXLIV");}
    if (resp==345){ System.out.println("La conversión es: CCCXLV");}
    if (resp==346){ System.out.println("La conversión es: CCCXLVI");}
    if (resp==347){ System.out.println("La conversión es: CCCXLVII");}
    if (resp==348){ System.out.println("La conversión es: CCCXLVIII");}
    if (resp==349){ System.out.println("La conversión es: CCCXLIX");}
    if (resp==350){ System.out.println("La conversión es: CCCL");}
    if (resp==351){ System.out.println("La conversión es: CCCLI");}
    if (resp==352){ System.out.println("La conversión es: CCCLII");}
    if (resp==353){ System.out.println("La conversión es: CCCLIII");}
    if (resp==354){ System.out.println("La conversión es: CCCLIV");}
    if (resp==355){ System.out.println("La conversión es: CCCLV");}
    if (resp==356){ System.out.println("La conversión es: CCCLVI");}
    if (resp==357){ System.out.println("La conversión es: CCCLVII");}  
    if (resp==358){ System.out.println("La conversión es: CCCLVIII");}
    if (resp==359){ System.out.println("La conversión es: CCCLIX");}
    if (resp==360){ System.out.println("La conversión es: CCCLX");}
    if (resp==361){ System.out.println("La conversión es: CCCLXI");}
    if (resp==362){ System.out.println("La conversión es: CCCLXII");}
    if (resp==363){ System.out.println("La conversión es: CCCLXIII");}
    if (resp==364){ System.out.println("La conversión es: CCCLXIV");}
    if (resp==365){ System.out.println("La conversión es: CCCLXV");}
    if (resp==366){ System.out.println("La conversión es: CCCLXVI");}
    if (resp==367){ System.out.println("La conversión es: CCCLXVII");}
    if (resp==368){ System.out.println("La conversión es: CCCLXVIII");}
    if (resp==369){ System.out.println("La conversión es: CCCLXIX");}
    if (resp==370){ System.out.println("La conversión es: CCCLXX");}
    if (resp==371){ System.out.println("La conversión es: CCCLXXI");}
    if (resp==372){ System.out.println("La conversión es: CCCLXXII");}
    if (resp==373){ System.out.println("La conversión es: CCCLXXIII");}
    if (resp==374){ System.out.println("La conversión es: CCCLXXIV");}
    if (resp==375){ System.out.println("La conversión es: CCCLXXV");}
    if (resp==376){ System.out.println("La conversión es: CCCLXXVI");}
    if (resp==377){ System.out.println("La conversión es: CCCLXXVII");}
    if (resp==378){ System.out.println("La conversión es: CCCLXXVIII");}
    if (resp==379){ System.out.println("La conversión es: CCCLXXIX");}
    if (resp==380){ System.out.println("La conversión es: CCCLXXX");}
    if (resp==381){ System.out.println("La conversión es: CCCLXXXI");}
    if (resp==382){ System.out.println("La conversión es: CCCLXXXII");}  
    if (resp==383){ System.out.println("La conversión es: CCCLXXXIII");}
    if (resp==384){ System.out.println("La conversión es: CCCLXXXIV");}
    if (resp==385){ System.out.println("La conversión es: CCCLXXXV");}
    if (resp==386){ System.out.println("La conversión es: CCCLXXXVI");}
    if (resp==387){ System.out.println("La conversión es: CCCLXXXVII");}
    if (resp==388){ System.out.println("La conversión es: CCCLXXXVIII");}
    if (resp==389){ System.out.println("La conversión es: CCCLXXXIX");}
    if (resp==390){ System.out.println("La conversión es: CCCXC");}
    if (resp==391){ System.out.println("La conversión es: CCCXCI");}
    if (resp==392){ System.out.println("La conversión es: CCCXCII");}
    if (resp==393){ System.out.println("La conversión es: CCCXCIII");}
    if (resp==394){ System.out.println("La conversión es: CCCXCIV");}
    if (resp==395){ System.out.println("La conversión es: CCCXCV");}
    if (resp==396){ System.out.println("La conversión es: CCCXCVI");}
    if (resp==397){ System.out.println("La conversión es: CCCXCVII");}
    if (resp==398){ System.out.println("La conversión es: CCCXCVIII");}
    if (resp==399){ System.out.println("La conversión es: CCCXCIX");}
    if (resp==400){ System.out.println("La conversión es: CD");}
    
    if (resp==401){ System.out.println("La conversión es: CDI");}
    if (resp==402){ System.out.println("La conversión es: CDII");}
    if (resp==403){ System.out.println("La conversión es: CDIII");}
    if (resp==404){ System.out.println("La conversión es: CDIV");}
    if (resp==405){ System.out.println("La conversión es: CDV");}
    if (resp==406){ System.out.println("La conversión es: CDVI");}
    if (resp==407){ System.out.println("La conversión es: CDVII");}
    if (resp==408){ System.out.println("La conversión es: CDVIII");}
    if (resp==409){ System.out.println("La conversión es: CDIX");}
    if (resp==410){ System.out.println("La conversión es: CDX");}
    if (resp==411){ System.out.println("La conversión es: CDXI");}
    if (resp==412){ System.out.println("La conversión es: CDXII");}
    if (resp==413){ System.out.println("La conversión es: CDXIII");}
    if (resp==414){ System.out.println("La conversión es: CDXIV");}
    if (resp==415){ System.out.println("La conversión es: CDXV");}
    if (resp==416){ System.out.println("La conversión es: CDXVI");}
    if (resp==417){ System.out.println("La conversión es: CDXVII");}
    if (resp==418){ System.out.println("La conversión es: CDXVIII");}
    if (resp==419){ System.out.println("La conversión es: CDXIX");}
    if (resp==420){ System.out.println("La conversión es: CDXX");}
    if (resp==421){ System.out.println("La conversión es: CDXXI");}
    if (resp==422){ System.out.println("La conversión es: CDXXII");}
    if (resp==423){ System.out.println("La conversión es: CDXXIII");}
    if (resp==424){ System.out.println("La conversión es: CDXXIV");}
    if (resp==425){ System.out.println("La conversión es: CDXXV");}
    if (resp==426){ System.out.println("La conversión es: CDXXVI");}
    if (resp==427){ System.out.println("La conversión es: CDXXVII");}
    if (resp==428){ System.out.println("La conversión es: CDXXVIII");}
    if (resp==429){ System.out.println("La conversión es: CDXXIX");}  
    if (resp==430){ System.out.println("La conversión es: CDXXX");}
    if (resp==431){ System.out.println("La conversión es: CDXXXI");}
    if (resp==432){ System.out.println("La conversión es: CDXXXII");}
    if (resp==433){ System.out.println("La conversión es: CDXXXIII");}
    if (resp==434){ System.out.println("La conversión es: CDXXXIV");}
    if (resp==435){ System.out.println("La conversión es: CDXXXV");}
    if (resp==436){ System.out.println("La conversión es: CDXXXVI");}
    if (resp==437){ System.out.println("La conversión es: CDXXXVII");}
    if (resp==438){ System.out.println("La conversión es: CDXXXVIII");}
    if (resp==439){ System.out.println("La conversión es: CDXXXIX");}
    if (resp==440){ System.out.println("La conversión es: CDXL");}
    if (resp==441){ System.out.println("La conversión es: CDXLI");}
    if (resp==442){ System.out.println("La conversión es: CDXLII");}
    if (resp==443){ System.out.println("La conversión es: CDXLIII");}
    if (resp==444){ System.out.println("La conversión es: CDXLIV");}
    if (resp==445){ System.out.println("La conversión es: CDXLV");}
    if (resp==446){ System.out.println("La conversión es: CDXLVI");}
    if (resp==447){ System.out.println("La conversión es: CDXLVII");}
    if (resp==448){ System.out.println("La conversión es: CDXLVIII");}
    if (resp==449){ System.out.println("La conversión es: CDXLIX");}
    if (resp==450){ System.out.println("La conversión es: CDL");}
    if (resp==451){ System.out.println("La conversión es: CDLI");}
    if (resp==452){ System.out.println("La conversión es: CDLII");}
    if (resp==453){ System.out.println("La conversión es: CDLIII");}
    if (resp==454){ System.out.println("La conversión es: CDLIV");}
    if (resp==455){ System.out.println("La conversión es: CDLV");}
    if (resp==456){ System.out.println("La conversión es: CDLCVI");}
    if (resp==457){ System.out.println("La conversión es: CDLVII");}  
    if (resp==458){ System.out.println("La conversión es: CDLVIII");}
    if (resp==459){ System.out.println("La conversión es: CDLIX");}
    if (resp==460){ System.out.println("La conversión es: CDLX");}
    if (resp==461){ System.out.println("La conversión es: CDLXI");}
    if (resp==462){ System.out.println("La conversión es: CDLXII");}
    if (resp==463){ System.out.println("La conversión es: CDLXIII");}
    if (resp==464){ System.out.println("La conversión es: CDLXIV");}
    if (resp==465){ System.out.println("La conversión es: CDLXV");}
    if (resp==466){ System.out.println("La conversión es: CDLXVI");}
    if (resp==467){ System.out.println("La conversión es: CDLXVII");}
    if (resp==468){ System.out.println("La conversión es: CDLXVIII");}
    if (resp==469){ System.out.println("La conversión es: CDLXIX");}
    if (resp==470){ System.out.println("La conversión es: CDLXX");}
    if (resp==471){ System.out.println("La conversión es: CDLXXI");}
    if (resp==472){ System.out.println("La conversión es: CDLXXII");}
    if (resp==473){ System.out.println("La conversión es: CDLXXIII");}
    if (resp==474){ System.out.println("La conversión es: CDLXXIV");}
    if (resp==475){ System.out.println("La conversión es: CDLXXV");}
    if (resp==476){ System.out.println("La conversión es: CDLXXVI");}
    if (resp==477){ System.out.println("La conversión es: CDLXXVII");}
    if (resp==478){ System.out.println("La conversión es: CDLXXVIII");}
    if (resp==479){ System.out.println("La conversión es: CLDXXIX");}
    if (resp==480){ System.out.println("La conversión es: CDLXXX");}
    if (resp==481){ System.out.println("La conversión es: CDLXXXI");}
    if (resp==482){ System.out.println("La conversión es: CDLXXXII");}  
    if (resp==483){ System.out.println("La conversión es: CDLXXXIII");}
    if (resp==484){ System.out.println("La conversión es: CDLXXXIV");}
    if (resp==485){ System.out.println("La conversión es: CDLXXXV");}
    if (resp==486){ System.out.println("La conversión es: CDLXXXVI");}
    if (resp==487){ System.out.println("La conversión es: CDLXXXVII");}
    if (resp==488){ System.out.println("La conversión es: CDLXXXVIII");}
    if (resp==489){ System.out.println("La conversión es: CDLDXXXIX");}
    if (resp==490){ System.out.println("La conversión es: CDXDC");}
    if (resp==491){ System.out.println("La conversión es: CDXCI");}
    if (resp==492){ System.out.println("La conversión es: CDXCII");}
    if (resp==493){ System.out.println("La conversión es: CDXCIII");}
    if (resp==494){ System.out.println("La conversión es: CDXCIV");}
    if (resp==495){ System.out.println("La conversión es: CDXCV");}
    if (resp==496){ System.out.println("La conversión es: CDXCVI");}
    if (resp==497){ System.out.println("La conversión es: CDXCVII");}
    if (resp==498){ System.out.println("La conversión es: CDXCVIII");}
    if (resp==499){ System.out.println("La conversión es: CDXCIX");}
    if (resp==500){ System.out.println("La conversión es: D");}

    if (resp==501){ System.out.println("La conversión es: DI");}
    if (resp==502){ System.out.println("La conversión es: DII");}
    if (resp==503){ System.out.println("La conversión es: DIII");}
    if (resp==504){ System.out.println("La conversión es: DIV");}  
    if (resp==505){ System.out.println("La conversión es: DV");}
    if (resp==506){ System.out.println("La conversión es: DVI");}
    if (resp==507){ System.out.println("La conversión es: DVII");}
    if (resp==508){ System.out.println("La conversión es: DVIII");}
    if (resp==509){ System.out.println("La conversión es: DIX");}
    if (resp==510){ System.out.println("La conversión es: DX");}
    if (resp==511){ System.out.println("La conversión es: DXI");}
    if (resp==512){ System.out.println("La conversión es: DXII");}
    if (resp==513){ System.out.println("La conversión es: DXIII");}
    if (resp==514){ System.out.println("La conversión es: DXIV");}
    if (resp==515){ System.out.println("La conversión es: DXV");}
    if (resp==516){ System.out.println("La conversión es: DXVI");}
    if (resp==517){ System.out.println("La conversión es: DXVII");}
    if (resp==518){ System.out.println("La conversión es: DXVIII");}
    if (resp==519){ System.out.println("La conversión es: DXIX");}
    if (resp==520){ System.out.println("La conversión es: DXX");}
    if (resp==521){ System.out.println("La conversión es: DXXI");}
    if (resp==522){ System.out.println("La conversión es: DXXII");}
    if (resp==523){ System.out.println("La conversión es: DXXIII");}
    if (resp==524){ System.out.println("La conversión es: DXXIV");}
    if (resp==525){ System.out.println("La conversión es: DXXV");}
    if (resp==526){ System.out.println("La conversión es: DXXVI");}
    if (resp==527){ System.out.println("La conversión es: DXXVII");}
    if (resp==528){ System.out.println("La conversión es: DXXVIII");}
    if (resp==529){ System.out.println("La conversión es: DXXIX");}  
    if (resp==530){ System.out.println("La conversión es: DXXX");}
    if (resp==531){ System.out.println("La conversión es: DXXXI");}
    if (resp==532){ System.out.println("La conversión es: DXXXII");}
    if (resp==533){ System.out.println("La conversión es: DXXXIII");}
    if (resp==534){ System.out.println("La conversión es: DXXXIV");}
    if (resp==535){ System.out.println("La conversión es: DXXXV");}
    if (resp==536){ System.out.println("La conversión es: DXXXVI");}
    if (resp==537){ System.out.println("La conversión es: DXXXVII");}
    if (resp==538){ System.out.println("La conversión es: DXXXVIII");}
    if (resp==539){ System.out.println("La conversión es: DXXXIX");}
    if (resp==540){ System.out.println("La conversión es: DXL");}
    if (resp==541){ System.out.println("La conversión es: DXLI");}
    if (resp==542){ System.out.println("La conversión es: DXLII");}
    if (resp==543){ System.out.println("La conversión es: DXLIII");}
    if (resp==544){ System.out.println("La conversión es: DXLIV");}
    if (resp==545){ System.out.println("La conversión es: DXLV");}
    if (resp==546){ System.out.println("La conversión es: DXLVI");}
    if (resp==547){ System.out.println("La conversión es: DXLVII");}
    if (resp==548){ System.out.println("La conversión es: DXLVIII");}
    if (resp==549){ System.out.println("La conversión es: DXLIX");}
    if (resp==550){ System.out.println("La conversión es: DL");}
    if (resp==551){ System.out.println("La conversión es: DLI");}
    if (resp==552){ System.out.println("La conversión es: DLII");}
    if (resp==553){ System.out.println("La conversión es: DLIII");}
    if (resp==554){ System.out.println("La conversión es: DLIV");}
    if (resp==555){ System.out.println("La conversión es: DLV");}
    if (resp==556){ System.out.println("La conversión es: DLVI");}
    if (resp==557){ System.out.println("La conversión es: DLVII");}  
    if (resp==558){ System.out.println("La conversión es: DLVIII");}
    if (resp==559){ System.out.println("La conversión es: DLIX");}
    if (resp==560){ System.out.println("La conversión es: DLX");}
    if (resp==561){ System.out.println("La conversión es: DLXI");}
    if (resp==562){ System.out.println("La conversión es: DLXII");}
    if (resp==563){ System.out.println("La conversión es: DLXIII");}
    if (resp==564){ System.out.println("La conversión es: DLXIV");}
    if (resp==565){ System.out.println("La conversión es: DLXV");}
    if (resp==566){ System.out.println("La conversión es: DLXVI");}
    if (resp==567){ System.out.println("La conversión es: DLXVII");}
    if (resp==568){ System.out.println("La conversión es: DLXVIII");}
    if (resp==569){ System.out.println("La conversión es: DLXIX");}
    if (resp==570){ System.out.println("La conversión es: DLXX");}
    if (resp==571){ System.out.println("La conversión es: DLXXI");}
    if (resp==572){ System.out.println("La conversión es: DLXXII");}
    if (resp==573){ System.out.println("La conversión es: DLXXIII");}
    if (resp==574){ System.out.println("La conversión es: DLXXIV");}
    if (resp==575){ System.out.println("La conversión es: DLXXV");}
    if (resp==576){ System.out.println("La conversión es: DLXXVI");}
    if (resp==577){ System.out.println("La conversión es: DLXXVII");}
    if (resp==578){ System.out.println("La conversión es: DLXXVIII");}
    if (resp==579){ System.out.println("La conversión es: DLXXIX");}
    if (resp==580){ System.out.println("La conversión es: DLXXX");}
    if (resp==581){ System.out.println("La conversión es: DLXXXI");}
    if (resp==582){ System.out.println("La conversión es: DLXXXII");}  
    if (resp==583){ System.out.println("La conversión es: DLXXXIII");}
    if (resp==584){ System.out.println("La conversión es: DLXXXIV");}
    if (resp==585){ System.out.println("La conversión es: DLXXXV");}
    if (resp==586){ System.out.println("La conversión es: DLXXXVI");}
    if (resp==587){ System.out.println("La conversión es: DLXXXVII");}
    if (resp==588){ System.out.println("La conversión es: DLXXXVIII");}
    if (resp==589){ System.out.println("La conversión es: DLXXXIX");}
    if (resp==590){ System.out.println("La conversión es: DXC");}
    if (resp==591){ System.out.println("La conversión es: DXCI");}
    if (resp==592){ System.out.println("La conversión es: DXCII");}
    if (resp==593){ System.out.println("La conversión es: DXCIII");}
    if (resp==594){ System.out.println("La conversión es: DXCIV");}
    if (resp==595){ System.out.println("La conversión es: DXCV");}
    if (resp==596){ System.out.println("La conversión es: DXCVI");}
    if (resp==597){ System.out.println("La conversión es: DXCVII");}
    if (resp==598){ System.out.println("La conversión es: DXCVIII");}
    if (resp==599){ System.out.println("La conversión es: DXCIX");}
    if (resp==600){ System.out.println("La conversión es: DC");}
    
    if (resp==601){ System.out.println("La conversión es: DCI");}
    if (resp==602){ System.out.println("La conversión es: DII");}
    if (resp==603){ System.out.println("La conversión es: DCIII");}
    if (resp==604){ System.out.println("La conversión es: DCIV");}
    if (resp==605){ System.out.println("La conversión es: DCV");}
    if (resp==606){ System.out.println("La conversión es: DCVI");}
    if (resp==607){ System.out.println("La conversión es: DCVII");}
    if (resp==608){ System.out.println("La conversión es: DCVIII");}
    if (resp==609){ System.out.println("La conversión es: DCIX");}
    if (resp==610){ System.out.println("La conversión es: DCX");}
    if (resp==611){ System.out.println("La conversión es: DCXI");}
    if (resp==612){ System.out.println("La conversión es: DCXII");}
    if (resp==613){ System.out.println("La conversión es: DCXIII");}
    if (resp==614){ System.out.println("La conversión es: DCXIV");}
    if (resp==615){ System.out.println("La conversión es: DCXV");}
    if (resp==616){ System.out.println("La conversión es: DCXVI");}
    if (resp==617){ System.out.println("La conversión es: DCXVII");}
    if (resp==618){ System.out.println("La conversión es: DCXVIII");}
    if (resp==619){ System.out.println("La conversión es: DCXIX");}
    if (resp==620){ System.out.println("La conversión es: DCXX");}
    if (resp==621){ System.out.println("La conversión es: DCXXI");}
    if (resp==622){ System.out.println("La conversión es: DCXXII");}
    if (resp==623){ System.out.println("La conversión es: DCXXIII");}
    if (resp==624){ System.out.println("La conversión es: DCXXIV");}
    if (resp==625){ System.out.println("La conversión es: DCXXV");}
    if (resp==626){ System.out.println("La conversión es: DCXXVI");}
    if (resp==627){ System.out.println("La conversión es: DCXXVII");}
    if (resp==628){ System.out.println("La conversión es: DCXXVIII");}
    if (resp==629){ System.out.println("La conversión es: DCXXIX");}  
    if (resp==630){ System.out.println("La conversión es: DCXXX");}
    if (resp==631){ System.out.println("La conversión es: DCXXXI");}
    if (resp==632){ System.out.println("La conversión es: DCXXXII");}
    if (resp==633){ System.out.println("La conversión es: DCXXXIII");}
    if (resp==634){ System.out.println("La conversión es: DCXXXIV");}
    if (resp==635){ System.out.println("La conversión es: DCXXXV");}
    if (resp==636){ System.out.println("La conversión es: DCXXXVI");}
    if (resp==637){ System.out.println("La conversión es: DCXXXVII");}
    if (resp==638){ System.out.println("La conversión es: DCXXXVIII");}
    if (resp==639){ System.out.println("La conversión es: DCXXXIX");}
    if (resp==640){ System.out.println("La conversión es: DCXL");}
    if (resp==641){ System.out.println("La conversión es: DCXLI");}
    if (resp==642){ System.out.println("La conversión es: DCXLII");}
    if (resp==643){ System.out.println("La conversión es: DCXLIII");}
    if (resp==644){ System.out.println("La conversión es: DCXLIV");}
    if (resp==645){ System.out.println("La conversión es: DCXLV");}
    if (resp==646){ System.out.println("La conversión es: DCXLVI");}
    if (resp==647){ System.out.println("La conversión es: DCXLVII");}
    if (resp==648){ System.out.println("La conversión es: DCXLVIII");}
    if (resp==649){ System.out.println("La conversión es: DCXLIX");}
    if (resp==650){ System.out.println("La conversión es: DCL");}
    if (resp==651){ System.out.println("La conversión es: DCLI");}
    if (resp==652){ System.out.println("La conversión es: DCLII");}
    if (resp==653){ System.out.println("La conversión es: DCLIII");}
    if (resp==654){ System.out.println("La conversión es: DCLIV");}
    if (resp==655){ System.out.println("La conversión es: DCLV");}
    if (resp==656){ System.out.println("La conversión es: DCLCVI");}
    if (resp==657){ System.out.println("La conversión es: DCLVII");}  
    if (resp==658){ System.out.println("La conversión es: DCLVIII");}
    if (resp==659){ System.out.println("La conversión es: DCLIX");}
    if (resp==660){ System.out.println("La conversión es: DCLX");}
    if (resp==661){ System.out.println("La conversión es: DCLXI");}
    if (resp==662){ System.out.println("La conversión es: DCLXII");}
    if (resp==663){ System.out.println("La conversión es: DCLXIII");}
    if (resp==664){ System.out.println("La conversión es: DCLXIV");}
    if (resp==665){ System.out.println("La conversión es: DCLXV");}
    if (resp==666){ System.out.println("La conversión es: DCLXVI");}
    if (resp==667){ System.out.println("La conversión es: DCLXVII");}
    if (resp==668){ System.out.println("La conversión es: DCLXVIII");}
    if (resp==669){ System.out.println("La conversión es: DCLXIX");}
    if (resp==670){ System.out.println("La conversión es: CLXX");}
    if (resp==671){ System.out.println("La conversión es: DCLXXI");}
    if (resp==672){ System.out.println("La conversión es: DCLXXII");}
    if (resp==673){ System.out.println("La conversión es: DCLXXIII");}
    if (resp==674){ System.out.println("La conversión es: DCLXXIV");}
    if (resp==675){ System.out.println("La conversión es: DCLXXV");}
    if (resp==676){ System.out.println("La conversión es: DCLXXVI");}
    if (resp==677){ System.out.println("La conversión es: DCLXXVII");}
    if (resp==678){ System.out.println("La conversión es: DCLXXVIII");}
    if (resp==679){ System.out.println("La conversión es: DCLXXIX");}
    if (resp==680){ System.out.println("La conversión es: DCLXXX");}
    if (resp==681){ System.out.println("La conversión es: DCLXXXI");}
    if (resp==682){ System.out.println("La conversión es: DCLXXXII");}  
    if (resp==683){ System.out.println("La conversión es: DCLXXXIII");}
    if (resp==684){ System.out.println("La conversión es: DCLXXXIV");}
    if (resp==685){ System.out.println("La conversión es: DCLXXXV");}
    if (resp==686){ System.out.println("La conversión es: DCLXXXVI");}
    if (resp==687){ System.out.println("La conversión es: DCLXXXVII");}
    if (resp==688){ System.out.println("La conversión es: DCLXXXVIII");}
    if (resp==689){ System.out.println("La conversión es: DCLXXXIX");}
    if (resp==690){ System.out.println("La conversión es: DCXC");}
    if (resp==691){ System.out.println("La conversión es: DCXCI");}
    if (resp==692){ System.out.println("La conversión es: DCXCII");}
    if (resp==693){ System.out.println("La conversión es: DCXCIII");}
    if (resp==694){ System.out.println("La conversión es: DCXCIV");}
    if (resp==695){ System.out.println("La conversión es: DCXCV");}
    if (resp==696){ System.out.println("La conversión es: DCXCVI");}
    if (resp==697){ System.out.println("La conversión es: DCXCVII");}
    if (resp==698){ System.out.println("La conversión es: DCXCVIII");}
    if (resp==699){ System.out.println("La conversión es: DCXCIX");}
    
    if (resp==700){ System.out.println("La conversión es: DCC");}
    if (resp==701){ System.out.println("La conversión es: DCCI");}
    if (resp==702){ System.out.println("La conversión es: DCCII");}
    if (resp==703){ System.out.println("La conversión es: DCCIII");}
    if (resp==704){ System.out.println("La conversión es: DCCIV");}  
    if (resp==705){ System.out.println("La conversión es: DCCV");}
    if (resp==706){ System.out.println("La conversión es: DCCVI");}
    if (resp==707){ System.out.println("La conversión es: DCCVII");}
    if (resp==708){ System.out.println("La conversión es: DCCVIII");}
    if (resp==709){ System.out.println("La conversión es: DCCIX");}
    if (resp==710){ System.out.println("La conversión es: DCCX");}
    if (resp==711){ System.out.println("La conversión es: DCCXI");}
    if (resp==712){ System.out.println("La conversión es: DCCXII");}
    if (resp==713){ System.out.println("La conversión es: DCCXIII");}
    if (resp==714){ System.out.println("La conversión es: DCCXIV");}
    if (resp==715){ System.out.println("La conversión es: DCCXV");}
    if (resp==716){ System.out.println("La conversión es: DCCXVI");}
    if (resp==717){ System.out.println("La conversión es: DCCXVII");}
    if (resp==718){ System.out.println("La conversión es: DCCXVIII");}
    if (resp==719){ System.out.println("La conversión es: DCCXIX");}
    if (resp==720){ System.out.println("La conversión es: DCCXX");}
    if (resp==721){ System.out.println("La conversión es: DCCXXI");}
    if (resp==722){ System.out.println("La conversión es: DCCXXII");}
    if (resp==723){ System.out.println("La conversión es: DCCXXIII");}
    if (resp==724){ System.out.println("La conversión es: DCCXXIV");}
    if (resp==725){ System.out.println("La conversión es: DCCXXV");}
    if (resp==726){ System.out.println("La conversión es: DCCXXVI");}
    if (resp==727){ System.out.println("La conversión es: DCCXXVII");}
    if (resp==728){ System.out.println("La conversión es: DCCXXVIII");}
    if (resp==729){ System.out.println("La conversión es: DCCXXIX");}  
    if (resp==730){ System.out.println("La conversión es: DCCXXX");}
    if (resp==731){ System.out.println("La conversión es: DCCXXXI");}
    if (resp==732){ System.out.println("La conversión es: DCCXXXII");}
    if (resp==733){ System.out.println("La conversión es: DCCXXXIII");}
    if (resp==734){ System.out.println("La conversión es: DCCXXXIV");}
    if (resp==735){ System.out.println("La conversión es: DCCXXXV");}
    if (resp==736){ System.out.println("La conversión es: DCCXXXVI");}
    if (resp==737){ System.out.println("La conversión es: DCCXXXVII");}
    if (resp==738){ System.out.println("La conversión es: DCCXXXVIII");}
    if (resp==739){ System.out.println("La conversión es: DCCXXXIX");}
    if (resp==740){ System.out.println("La conversión es: DCCXL");}
    if (resp==741){ System.out.println("La conversión es: DCCXLI");}
    if (resp==742){ System.out.println("La conversión es: DCCXLII");}
    if (resp==743){ System.out.println("La conversión es: DCCXLIII");}
    if (resp==744){ System.out.println("La conversión es: DCCXLIV");}
    if (resp==745){ System.out.println("La conversión es: DCCXLV");}
    if (resp==746){ System.out.println("La conversión es: DCCXLVI");}
    if (resp==747){ System.out.println("La conversión es: DCCXLVII");}
    if (resp==748){ System.out.println("La conversión es: DCCXLVIII");}
    if (resp==749){ System.out.println("La conversión es: DCCXLIX");}
    if (resp==750){ System.out.println("La conversión es: DCCL");}
    if (resp==751){ System.out.println("La conversión es: DCCCLI");}
    if (resp==752){ System.out.println("La conversión es: DCCLII");}
    if (resp==753){ System.out.println("La conversión es: DCCLIII");}
    if (resp==754){ System.out.println("La conversión es: DCCLIV");}
    if (resp==755){ System.out.println("La conversión es: DCCLV");}
    if (resp==756){ System.out.println("La conversión es: DCCLVI");}
    if (resp==757){ System.out.println("La conversión es: DCCLVII");}  
    if (resp==758){ System.out.println("La conversión es: DCCLVIII");}
    if (resp==759){ System.out.println("La conversión es: DCCLIX");}
    if (resp==760){ System.out.println("La conversión es: DCCLX");}
    if (resp==761){ System.out.println("La conversión es: DCCLXI");}
    if (resp==762){ System.out.println("La conversión es: DCCLXII");}
    if (resp==763){ System.out.println("La conversión es: DCCLXIII");}
    if (resp==764){ System.out.println("La conversión es: DCCLXIV");}
    if (resp==765){ System.out.println("La conversión es: DCCLXV");}
    if (resp==766){ System.out.println("La conversión es: DCCLXVI");}
    if (resp==767){ System.out.println("La conversión es: DCCLXVII");}
    if (resp==768){ System.out.println("La conversión es: DCCLXVIII");}
    if (resp==769){ System.out.println("La conversión es: DCCLXIX");}
    if (resp==770){ System.out.println("La conversión es: DCCLXX");}
    if (resp==771){ System.out.println("La conversión es: DCCLXXI");}
    if (resp==772){ System.out.println("La conversión es: DCCLXXII");}
    if (resp==773){ System.out.println("La conversión es: DCCLXXIII");}
    if (resp==774){ System.out.println("La conversión es: DCCLXXIV");}
    if (resp==775){ System.out.println("La conversión es: DCCLXXV");}
    if (resp==776){ System.out.println("La conversión es: DCCLXXVI");}
    if (resp==777){ System.out.println("La conversión es: DCCLXXVII");}
    if (resp==778){ System.out.println("La conversión es: DCCLXXVIII");}
    if (resp==779){ System.out.println("La conversión es: DCCLXXIX");}
    if (resp==780){ System.out.println("La conversión es: DCCLXXX");}
    if (resp==781){ System.out.println("La conversión es: DCCLXXXI");}
    if (resp==782){ System.out.println("La conversión es: DCCLXXXII");}  
    if (resp==783){ System.out.println("La conversión es: DCCLXXXIII");}
    if (resp==784){ System.out.println("La conversión es: DCCLXXXIV");}
    if (resp==785){ System.out.println("La conversión es: DCCLXXXV");}
    if (resp==786){ System.out.println("La conversión es: DCCLXXXVI");}
    if (resp==787){ System.out.println("La conversión es: DCCLXXXVII");}
    if (resp==788){ System.out.println("La conversión es: DCCLXXXVIII");}
    if (resp==789){ System.out.println("La conversión es: DCCLXXXIX");}
    if (resp==790){ System.out.println("La conversión es: DCCXC");}
    if (resp==791){ System.out.println("La conversión es: DCCXCI");}
    if (resp==792){ System.out.println("La conversión es: DCCXCII");}
    if (resp==793){ System.out.println("La conversión es: DCCXCIII");}
    if (resp==794){ System.out.println("La conversión es: DCCXCIV");}
    if (resp==795){ System.out.println("La conversión es: DCCXCV");}
    if (resp==796){ System.out.println("La conversión es: DCCXCVI");}
    if (resp==797){ System.out.println("La conversión es: DCCXCVII");}
    if (resp==798){ System.out.println("La conversión es: DCCXCVIII");}
    if (resp==799){ System.out.println("La conversión es: DCCXCIX");}
    if (resp==800){ System.out.println("La conversión es: DCCC");}
   
    if (resp==801){ System.out.println("La conversión es: DCCCI");}
    if (resp==802){ System.out.println("La conversión es: DCCCII");}
    if (resp==803){ System.out.println("La conversión es: DCCCIII");}
    if (resp==804){ System.out.println("La conversión es: DCCCIV");}  
    if (resp==805){ System.out.println("La conversión es: DCCCV");}
    if (resp==806){ System.out.println("La conversión es: DCCCVI");}
    if (resp==807){ System.out.println("La conversión es: DCCCVII");}
    if (resp==808){ System.out.println("La conversión es: DCCCVIII");}
    if (resp==809){ System.out.println("La conversión es: DCCCIX");}
    if (resp==810){ System.out.println("La conversión es: DCCCX");}
    if (resp==811){ System.out.println("La conversión es: DCCCXI");}
    if (resp==812){ System.out.println("La conversión es: DCCCXII");}
    if (resp==813){ System.out.println("La conversión es: DCCCXIII");}
    if (resp==814){ System.out.println("La conversión es: DCCCXIV");}
    if (resp==815){ System.out.println("La conversión es: DCCCXV");}
    if (resp==816){ System.out.println("La conversión es: DCCCXVI");}
    if (resp==817){ System.out.println("La conversión es: DCCCXVII");}
    if (resp==818){ System.out.println("La conversión es: DCCCXVIII");}
    if (resp==819){ System.out.println("La conversión es: DCCCXIX");}
    if (resp==820){ System.out.println("La conversión es: DCCCXX");}
    if (resp==821){ System.out.println("La conversión es: DCCCXXI");}
    if (resp==822){ System.out.println("La conversión es: DCCCXXII");}
    if (resp==823){ System.out.println("La conversión es: DCCCXXIII");}
    if (resp==824){ System.out.println("La conversión es: DCCCXXIV");}
    if (resp==825){ System.out.println("La conversión es: DCCCXXV");}
    if (resp==826){ System.out.println("La conversión es: DCCCXXVI");}
    if (resp==827){ System.out.println("La conversión es: DCCCXXVII");}
    if (resp==828){ System.out.println("La conversión es: DCCCXXVIII");}
    if (resp==829){ System.out.println("La conversión es: DCCCXXIX");}  
    if (resp==830){ System.out.println("La conversión es: DCCCXXX");}
    if (resp==831){ System.out.println("La conversión es: DCCCXXXI");}
    if (resp==832){ System.out.println("La conversión es: DCCCXXXII");}
    if (resp==833){ System.out.println("La conversión es: DCCCXXXIII");}
    if (resp==834){ System.out.println("La conversión es: DCCCXXXIV");}
    if (resp==835){ System.out.println("La conversión es: DCCCXXXV");}
    if (resp==836){ System.out.println("La conversión es: DCCCXXXVI");}
    if (resp==837){ System.out.println("La conversión es: DCCCXXXVII");}
    if (resp==838){ System.out.println("La conversión es: DCCCXXXVIII");}
    if (resp==839){ System.out.println("La conversión es: DCCCXXXIX");}
    if (resp==840){ System.out.println("La conversión es: DCCCXL");}
    if (resp==841){ System.out.println("La conversión es: DCCCXLI");}
    if (resp==842){ System.out.println("La conversión es: DCCCXLII");}
    if (resp==843){ System.out.println("La conversión es: DCCCXLIII");}
    if (resp==844){ System.out.println("La conversión es: DCCCXLIV");}
    if (resp==845){ System.out.println("La conversión es: DCCCXLV");}
    if (resp==846){ System.out.println("La conversión es: DCCCXLVI");}
    if (resp==847){ System.out.println("La conversión es: DCCCXLVII");}
    if (resp==848){ System.out.println("La conversión es: DCCCXLVIII");}
    if (resp==849){ System.out.println("La conversión es: DCCCXLIX");}
    if (resp==850){ System.out.println("La conversión es: DCCCL");}
    if (resp==851){ System.out.println("La conversión es: DCCCLI");}
    if (resp==852){ System.out.println("La conversión es: DCCCLII");}
    if (resp==853){ System.out.println("La conversión es: DCCCLIII");}
    if (resp==854){ System.out.println("La conversión es: DCCCLIV");}
    if (resp==855){ System.out.println("La conversión es: DCCCLV");}
    if (resp==856){ System.out.println("La conversión es: DCCCLVI");}
    if (resp==857){ System.out.println("La conversión es: DCCCLVII");}  
    if (resp==858){ System.out.println("La conversión es: DCCCLVIII");}
    if (resp==859){ System.out.println("La conversión es: DCCCLIX");}
    if (resp==860){ System.out.println("La conversión es: DCCCLX");}
    if (resp==861){ System.out.println("La conversión es: DCCCLXI");}
    if (resp==862){ System.out.println("La conversión es: DCCCLXII");}
    if (resp==863){ System.out.println("La conversión es: DCCCLXIII");}
    if (resp==864){ System.out.println("La conversión es: DCCCLXIV");}
    if (resp==865){ System.out.println("La conversión es: DCCCLXV");}
    if (resp==866){ System.out.println("La conversión es: DCCCLXVI");}
    if (resp==867){ System.out.println("La conversión es: DCCCLXVII");}
    if (resp==868){ System.out.println("La conversión es: DCCCLXVIII");}
    if (resp==869){ System.out.println("La conversión es: DCCCLXIX");}
    if (resp==870){ System.out.println("La conversión es: DCCCLXX");}
    if (resp==871){ System.out.println("La conversión es: DCCCLXXI");}
    if (resp==872){ System.out.println("La conversión es: DCCCLXXII");}
    if (resp==873){ System.out.println("La conversión es: DCCCLXXIII");}
    if (resp==874){ System.out.println("La conversión es: DCCCLXXIV");}
    if (resp==875){ System.out.println("La conversión es: DCCCLXXV");}
    if (resp==876){ System.out.println("La conversión es: DCCCLXXVI");}
    if (resp==877){ System.out.println("La conversión es: DCCCLXXVII");}
    if (resp==878){ System.out.println("La conversión es: DCCCLXXVIII");}
    if (resp==879){ System.out.println("La conversión es: DCCCLXXIX");}
    if (resp==880){ System.out.println("La conversión es: DCCCLXXX");}
    if (resp==881){ System.out.println("La conversión es: DCCCLXXXI");}
    if (resp==882){ System.out.println("La conversión es: DCCCLXXXII");}  
    if (resp==883){ System.out.println("La conversión es: DCCCLXXXIII");}
    if (resp==884){ System.out.println("La conversión es: DCCCLXXXIV");}
    if (resp==885){ System.out.println("La conversión es: DCCCLXXXV");}
    if (resp==886){ System.out.println("La conversión es: DCCCLXXXVI");}
    if (resp==887){ System.out.println("La conversión es: DCCCLXXXVII");}
    if (resp==888){ System.out.println("La conversión es: DCCCLXXXVIII");}
    if (resp==889){ System.out.println("La conversión es: DCCCLXXXIX");}
    if (resp==890){ System.out.println("La conversión es: DCCCXC");}
    if (resp==891){ System.out.println("La conversión es: DCCCXCI");}
    if (resp==892){ System.out.println("La conversión es: DCCCXCII");}
    if (resp==893){ System.out.println("La conversión es: DCCCXCIII");}
    if (resp==894){ System.out.println("La conversión es: DCCCXCIV");}
    if (resp==895){ System.out.println("La conversión es: DCCCXCV");}
    if (resp==896){ System.out.println("La conversión es: DCCCXCVI");}
    if (resp==897){ System.out.println("La conversión es: DCCCXCVII");}
    if (resp==898){ System.out.println("La conversión es: DCCCXCVIII");}
    if (resp==899){ System.out.println("La conversión es: DCCCXCIX");}
    
    if (resp==900){ System.out.println("La conversión es: CM");}
    if (resp==901){ System.out.println("La conversión es: CMI");}
    if (resp==902){ System.out.println("La conversión es: CMII");}
    if (resp==903){ System.out.println("La conversión es: CMIII");}
    if (resp==904){ System.out.println("La conversión es: CMIV");}
    if (resp==905){ System.out.println("La conversión es: CMV");}
    if (resp==906){ System.out.println("La conversión es: CMVI");}
    if (resp==907){ System.out.println("La conversión es: CMVII");}
    if (resp==908){ System.out.println("La conversión es: CMVIII");}
    if (resp==909){ System.out.println("La conversión es: CMIX");}
    if (resp==910){ System.out.println("La conversión es: CMX");}
    if (resp==911){ System.out.println("La conversión es: CMXI");}
    if (resp==912){ System.out.println("La conversión es: CMXII");}
    if (resp==913){ System.out.println("La conversión es: CMXIII");}
    if (resp==914){ System.out.println("La conversión es: CMXIV");}
    if (resp==915){ System.out.println("La conversión es: CMXV");}
    if (resp==916){ System.out.println("La conversión es: CMXVI");}
    if (resp==917){ System.out.println("La conversión es: CMXVII");}
    if (resp==918){ System.out.println("La conversión es: CMXVIII");}
    if (resp==919){ System.out.println("La conversión es: CMXIX");}
    if (resp==920){ System.out.println("La conversión es: CMXX");}
    if (resp==921){ System.out.println("La conversión es: CMXXI");}
    if (resp==922){ System.out.println("La conversión es: CMXXII");}
    if (resp==923){ System.out.println("La conversión es: CMXXIII");}
    if (resp==924){ System.out.println("La conversión es: CMXXIV");}
    if (resp==925){ System.out.println("La conversión es: CMXXV");}
    if (resp==926){ System.out.println("La conversión es: CMXXVI");}
    if (resp==927){ System.out.println("La conversión es: CMXXVII");}
    if (resp==928){ System.out.println("La conversión es: CMXXVIII");}
    if (resp==929){ System.out.println("La conversión es: CMXXIX");}  
    if (resp==930){ System.out.println("La conversión es: CMXXX");}
    if (resp==931){ System.out.println("La conversión es: CMXXXI");}
    if (resp==932){ System.out.println("La conversión es: CMXXXII");}
    if (resp==933){ System.out.println("La conversión es: CMXXXIII");}
    if (resp==934){ System.out.println("La conversión es: CMXXXIV");}
    if (resp==935){ System.out.println("La conversión es: CMXXXV");}
    if (resp==936){ System.out.println("La conversión es: CMXXXVI");}
    if (resp==937){ System.out.println("La conversión es: CMXXXVII");}
    if (resp==938){ System.out.println("La conversión es: CMXXXVIII");}
    if (resp==939){ System.out.println("La conversión es: CMXXXIX");}
    if (resp==940){ System.out.println("La conversión es: CMXL");}
    if (resp==941){ System.out.println("La conversión es: CMXLI");}
    if (resp==942){ System.out.println("La conversión es: CMXLII");}
    if (resp==943){ System.out.println("La conversión es: CMXLIII");}
    if (resp==944){ System.out.println("La conversión es: CMXLIV");}
    if (resp==945){ System.out.println("La conversión es: CMXLV");}
    if (resp==946){ System.out.println("La conversión es: CMXLVI");}
    if (resp==947){ System.out.println("La conversión es: CMXLVII");}
    if (resp==948){ System.out.println("La conversión es: CMXLVIII");}
    if (resp==949){ System.out.println("La conversión es: CMXLIX");}
    if (resp==950){ System.out.println("La conversión es: CML");}
    if (resp==951){ System.out.println("La conversión es: CMLI");}
    if (resp==952){ System.out.println("La conversión es: CMLII");}
    if (resp==953){ System.out.println("La conversión es: CMLIII");}
    if (resp==954){ System.out.println("La conversión es: CMLIV");}
    if (resp==955){ System.out.println("La conversión es: CMLV");}
    if (resp==956){ System.out.println("La conversión es: CMLCVI");}
    if (resp==957){ System.out.println("La conversión es: CMLVII");}  
    if (resp==958){ System.out.println("La conversión es: CMLVIII");}
    if (resp==959){ System.out.println("La conversión es: CMLIX");}
    if (resp==960){ System.out.println("La conversión es: CMLX");}
    if (resp==961){ System.out.println("La conversión es: CMLXI");}
    if (resp==962){ System.out.println("La conversión es: CMLXII");}
    if (resp==963){ System.out.println("La conversión es: CMLXIII");}
    if (resp==964){ System.out.println("La conversión es: CMLXIV");}
    if (resp==965){ System.out.println("La conversión es: CMLXV");}
    if (resp==966){ System.out.println("La conversión es: CMLXVI");}
    if (resp==967){ System.out.println("La conversión es: CMLXVII");}
    if (resp==968){ System.out.println("La conversión es: CMLXVIII");}
    if (resp==969){ System.out.println("La conversión es: CMLXIX");}
    if (resp==970){ System.out.println("La conversión es: CMLXX");}
    if (resp==971){ System.out.println("La conversión es: CMLXXI");}
    if (resp==972){ System.out.println("La conversión es: CMLXXII");}
    if (resp==973){ System.out.println("La conversión es: CMLXXIII");}
    if (resp==974){ System.out.println("La conversión es: CMLXXIV");}
    if (resp==975){ System.out.println("La conversión es: CMLXXV");}
    if (resp==976){ System.out.println("La conversión es: CMLXXVI");}
    if (resp==977){ System.out.println("La conversión es: CMLXXVII");}
    if (resp==978){ System.out.println("La conversión es: CMLXXVIII");}
    if (resp==979){ System.out.println("La conversión es: CMLXXIX");}
    if (resp==980){ System.out.println("La conversión es: CMLXXX");}
    if (resp==981){ System.out.println("La conversión es: CMLXXXI");}
    if (resp==982){ System.out.println("La conversión es: CMLXXXII");}  
    if (resp==983){ System.out.println("La conversión es: CMLXXXIII");}
    if (resp==984){ System.out.println("La conversión es: CMLXXXIV");}
    if (resp==985){ System.out.println("La conversión es: CMLXXXV");}
    if (resp==986){ System.out.println("La conversión es: CMLXXXVI");}
    if (resp==987){ System.out.println("La conversión es: CMLXXXVII");}
    if (resp==988){ System.out.println("La conversión es: CMLXXXVIII");}
    if (resp==989){ System.out.println("La conversión es: CMLXXXIX");}
    if (resp==990){ System.out.println("La conversión es: CMXC");}
    if (resp==991){ System.out.println("La conversión es: CMXCI");}
    if (resp==992){ System.out.println("La conversión es: CMXCII");}
    if (resp==993){ System.out.println("La conversión es: CMXCIII");}
    if (resp==994){ System.out.println("La conversión es: CMXCIV");}
    if (resp==995){ System.out.println("La conversión es: CMXCV");}
    if (resp==996){ System.out.println("La conversión es: CMXCVI");}
    if (resp==997){ System.out.println("La conversión es: CMXCVII");}
    if (resp==998){ System.out.println("La conversión es: CMXCVIII");}
    if (resp==999){ System.out.println("La conversión es: CMXCIX");}
    if (resp==1000){ System.out.println("La conversión es: M");}
    
    }
}